name: Serverless deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: zetifi/.github-private/.github/workflows/serverless-deploy.yml@master
    with:
      environment: 'live'
    secrets: inherit
